repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: &excludes |
            (?x)^(
              .+\.(md|bin)|
              examples/stm32_example/.+
            )$
      - id: end-of-file-fixer
        exclude: *excludes
      - id: mixed-line-ending
        args: ['-f=lf']
        exclude: *excludes
  - repo: https://github.com/igrr/astyle_py.git
    rev: v0.9.0
    hooks:
      - id: astyle_py
        args: [--options=astyle_config]
        exclude: *excludes
